Update signalhubws dependency
QwantResearch/masq-app pull request #178
Opened 2019-10-09 09:54 UTC by sujeebant

2019-10-09 15:03 UTC, G-Ray commented
We need to update this PR once other PRs are merged

2019-10-11 10:00 UTC, G-Ray approved these changes

2019-10-11 10:01 UTC, G-Ray requested changes

2019-10-11 10:01 UTC, G-Ray commented on package.json
> +    "signalhubws": "git+https://github.com/soyuka/signalhubws#v1.0.12",
Just use signalhubws from npm

2019-10-11 10:15 UTC, sujeebant commented on package.json
> +    "signalhubws": "git+https://github.com/soyuka/signalhubws#v1.0.12",
:+1:

2019-10-11 10:18 UTC, G-Ray approved these changes

2019-10-11 13:10 UTC, merged